name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use a .NET Core version
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests
        env:
          ASPNETCORE_ENVIRONMENT: Test
        run: dotnet test --verbosity normal
